LOCAL_PATH := $(call my-dir)

# ═══════════════════════════════════════════════════════════════════
# VMP Bytecode Library — auto-generated bytecode programs
# ═══════════════════════════════════════════════════════════════════
include $(CLEAR_VARS)
LOCAL_MODULE := lianyu_vmp_bytecode
LOCAL_SRC_FILES := vm-bytecode.cpp
LOCAL_CPPFLAGS := -DPRODUCTION_BUILD -Os -fvisibility=hidden -fdata-sections -ffunction-sections
LOCAL_CPPFLAGS += -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-ident
LOCAL_CPPFLAGS += -fmerge-all-constants
LOCAL_LDLIBS := -llog
LOCAL_CPP_FEATURES := exceptions rtti
LOCAL_LDFLAGS := -Wl,--gc-sections -Wl,-s
include $(BUILD_STATIC_LIBRARY)

# ═══════════════════════════════════════════════════════════════════
# Main Security SO — liblianyu_security.so
# SO decrypt stub in decrypt-stub.cpp, VMP bytecode as static lib
# ═══════════════════════════════════════════════════════════════════
include $(CLEAR_VARS)
LOCAL_MODULE := lianyu_security
LOCAL_SRC_FILES := decrypt-stub.cpp native-bridge.cpp whitebox-aes.cpp vm-engine.cpp zero-trust.cpp kms-engine.cpp sm-cipher.cpp memory-guard.cpp string-table.cpp dex-packer.cpp g_vmp_payload_data.cpp integrity-guard.cpp apk-sig-key.cpp native_safety.cpp native_codec.cpp
LOCAL_CPPFLAGS := -DPRODUCTION_BUILD -U_FORTIFY_SOURCE -Os -fvisibility=hidden -fdata-sections -ffunction-sections -fomit-frame-pointer -fno-stack-protector
LOCAL_CPPFLAGS += -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-ident
LOCAL_CPPFLAGS += -fmerge-all-constants -fno-inline-functions-called-once

LOCAL_LDLIBS := -llog -landroid -ljnigraphics
LOCAL_CPP_FEATURES := exceptions rtti
LOCAL_STATIC_LIBRARIES := lianyu_vmp_bytecode
LOCAL_LDFLAGS := -Wl,--version-script=$(LOCAL_PATH)/version-script.map -Wl,--gc-sections -Wl,-s -Wl,-z,separate-code -Wl,-u,_lianyu_text_decrypt_ptr -Wl,-u,g_vmp_payload -Wl,-u,Java_com_lianyu_ai_security_KmsProvider_nativeInit -Wl,-u,kms_provider_register_natives

include $(BUILD_SHARED_LIBRARY)

# ═══════════════════════════════════════════════════════════════════
# Dex2C Native Library (Phase 2-3)
# ═══════════════════════════════════════════════════════════════════
include $(CLEAR_VARS)
LOCAL_MODULE := lianyu_dex2c
LOCAL_SRC_FILES := generated/dex2c_methods.cpp
LOCAL_CPPFLAGS := -DPRODUCTION_BUILD -Os -fvisibility=hidden -fdata-sections -ffunction-sections
LOCAL_CPPFLAGS += -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-ident
LOCAL_CPPFLAGS += -fmerge-all-constants
LOCAL_LDLIBS := -llog
LOCAL_CPP_FEATURES := exceptions rtti
LOCAL_LDFLAGS := -Wl,-s -Wl,--gc-sections
include $(BUILD_SHARED_LIBRARY)

# ═══════════════════════════════════════════════════════════════════
# Shell Library — liblianyu_shell.so
# ═══════════════════════════════════════════════════════════════════
include $(CLEAR_VARS)
LOCAL_MODULE := lianyu_shell
LOCAL_SRC_FILES := dex-extractor.cpp
LOCAL_CPPFLAGS := -Os -fvisibility=hidden -fdata-sections -ffunction-sections
LOCAL_CPPFLAGS += -fno-unwind-tables -fno-asynchronous-unwind-tables
LOCAL_LDLIBS := -llog
LOCAL_CPP_FEATURES := exceptions rtti
LOCAL_LDFLAGS := -Wl,--version-script=$(LOCAL_PATH)/version-script-shell.map -Wl,--gc-sections
include $(BUILD_SHARED_LIBRARY)
