// Runtime decrypt stub — placeholder for VMP linker trampoline.
// Generated by build_shell_apk.py in production builds.
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// Symbol forced by linker: -Wl,-u,_lianyu_text_decrypt_ptr
extern void* lianyu_text_decrypt_ptr;

// D2 .text self-decryption — real impl injected by build_shell_apk.py
void lianyu_d2_decrypt();

#ifdef __cplusplus
}
#endif
