// Auto-generated per-build VMP configuration — DO NOT COMMIT
// Each APK build gets randomized algorithm constants.
// Generated by gen_payload_cpp.py at build time.

#ifndef LIANYU_VMP_CONFIG_H
#define LIANYU_VMP_CONFIG_H

#include <stdint.h>

// ── LCG parameters for scatter_key_positions ──────────────────────
// state = (state * VMP_LCG_MUL + VMP_LCG_ADD) & 0xFFFFFFFF
#define VMP_LCG_MUL  0x3D16D707u
#define VMP_LCG_ADD  0x74FEA504u

// ── XOR deobfuscation parameters for deobfuscate_key ──────────────
// key_out[i] = obf_key[i] ^ seed[(i * VMP_XOR_STRIDE) & 3] ^ (i * VMP_XOR_MULT)
#define VMP_XOR_MULT    0xA4u
#define VMP_XOR_STRIDE  0x05u

// ── Integrity seed multiplier (vm-engine.cpp vm_init) ─────────────
// Replaces hardcoded 1103515245 with per-build random value.
#define VMP_INTEGRITY_MUL  0xF67087CFu

// ── Seed (cert CRC32, for reference only — not used at runtime) ───
#define VMP_BUILD_SEED  0xDEADBEEFu

// ── Shell method/field name obfuscation (per-build random) ─────────
// These replace the hardcoded JNI names in Kotlin shell + C++ gMethods.
// C++:  RegisterNatives with VMP_SHELL_LOAD_PAYLOAD instead of "nativeLoadPayload"
//       GetStaticFieldID with VMP_SHELL_DEX_LOADER instead of "sDexClassLoader"
//       GetStaticFieldID with VMP_SHELL_REAL_APP_CLASS instead of "sRealAppClass"
// Kotlin: external fun dByscKBZMeif(...) replaces nativeLoadPayload
//         @JvmStatic var c6J4mqpREjD5 replaces sDexClassLoader
//         @JvmStatic var aU4jD26mJ7SXoRd replaces sRealAppClass
#define VMP_SHELL_LOAD_PAYLOAD   "dByscKBZMeif"
#define VMP_SHELL_DEX_LOADER     "c6J4mqpREjD5"
#define VMP_SHELL_REAL_APP_CLASS "aU4jD26mJ7SXoRd"

#endif // LIANYU_VMP_CONFIG_H
