// Auto-generated per-build VMP configuration — DO NOT COMMIT
// Each APK build gets randomized algorithm constants.
// Generated by gen_payload_cpp.py at build time.

#ifndef LIANYU_VMP_CONFIG_H
#define LIANYU_VMP_CONFIG_H

#include <stdint.h>

// ── LCG parameters for scatter_key_positions ──────────────────────
// state = (state * VMP_LCG_MUL + VMP_LCG_ADD) & 0xFFFFFFFF
#define VMP_LCG_MUL  0x5E00B3C7u
#define VMP_LCG_ADD  0x5C09C627u

// ── XOR deobfuscation parameters for deobfuscate_key ──────────────
// key_out[i] = obf_key[i] ^ seed[(i * VMP_XOR_STRIDE) & 3] ^ (i * VMP_XOR_MULT)
#define VMP_XOR_MULT    0xC4u
#define VMP_XOR_STRIDE  0x07u

// ── Integrity seed multiplier (vm-engine.cpp vm_init) ─────────────
// Replaces hardcoded 1103515245 with per-build random value.
#define VMP_INTEGRITY_MUL  0x07C33447u

// ── Seed (cert CRC32, for reference only — not used at runtime) ───
#define VMP_BUILD_SEED  0xAAF0BF89u

// ── Shell method/field name obfuscation (per-build random) ─────────
// These replace the hardcoded JNI names in Kotlin shell + C++ gMethods.
// C++:  RegisterNatives with VMP_SHELL_LOAD_PAYLOAD instead of "nativeLoadPayload"
//       GetStaticFieldID with VMP_SHELL_DEX_LOADER instead of "sDexClassLoader"
//       GetStaticFieldID with VMP_SHELL_REAL_APP_CLASS instead of "sRealAppClass"
// Kotlin: external fun dJ414UTwisYq(...) replaces nativeLoadPayload
//         @JvmStatic var ceAPV7xKK1YDE replaces sDexClassLoader
//         @JvmStatic var _pg9fWGG63DU7 replaces sRealAppClass
#define VMP_SHELL_LOAD_PAYLOAD   "dJ414UTwisYq"
#define VMP_SHELL_DEX_LOADER     "ceAPV7xKK1YDE"
#define VMP_SHELL_REAL_APP_CLASS "_pg9fWGG63DU7"

#endif // LIANYU_VMP_CONFIG_H
