/*
 * White-Box AES-256 (Chow-style) — Table-Driven Implementation
 *
 * The AES key is PERMANENTLY embedded in the pre-computed lookup tables.
 * At runtime:
 *   - NO AES key schedule exists in memory
 *   - NO subkeys are derived during execution
 *   - Only table lookups + XOR operations (constant-time)
 *   - Anti-DFA: integrity checksums per round
 *
 * Table layout for AES-256 (14 rounds, 16 T-Boxes per round):
 *   T-Box: 256 entries × 4 bytes × 16 positions × 14 rounds = 229KB
 *   Checksums: 16 bytes × 14 rounds = 224 bytes
 */

#include "whitebox-aes.h"
#include <cstring>
#include <cstdlib>

/* ================================================================
 * Generated lookup tables (key-dependent, embedded at compile time)
 * Generated by: tools/gen_wb_tables.py / wb_aes_keygen.py
 * ================================================================
 * The tables below are DEMO / placeholder tables generated for a
 * test key. In production, run gen_wb_tables.py with the actual
 * deployment key and replace this section.
 *
 * FORMAT:
 *   g_wb_tbox[round][position][input_byte] = 4-byte output
 *   g_wb_checksum[round] = expected XOR of all T-Box outputs
 *   g_wb_ext_in/out = external input/output encodings
 * ================================================================ */

/* Placeholder: these will be regenerated by gen_wb_tables.py.
 * To regenerate: python3 tools/gen_wb_tables.py --key hex:... > tables.inc
 */
#include "wb_tables.inc"  /* generated: g_wb_tbox, g_wb_checksum, g_wb_ext */
#include <time.h>
#include "obfuscate.h"
#include "zero-trust.h"  /* ZT state gating for crypto ops */
#include <android/log.h>
#include <unistd.h>

/* Integrity state */
static volatile int g_wb_inited = 0;
static volatile int g_wb_tampered = 0;
static volatile int g_wb_obfuscated = 0;  /* L2 active? */
static volatile int g_wb_checksums_placeholder = 0;  /* 1 = demo tables, checksums are all 0x00 */

/* Self-contained CRC32 for T-Box integrity verification.
 * Pre-computed values in g_wb_checksum[] must match (generated by gen_wb_tables.py). */
static uint32_t compute_tbox_crc32(const uint8_t* state, int r) {
    (void)state;
    uint32_t crc = 0xFFFFFFFFu;
    for (int pos = 0; pos < 16; pos++) {
        for (int e = 0; e < 1024; e++) {
            const uint8_t* data = &g_wb_tbox[r][pos][e * 4];
            for (int b = 0; b < 4; b++) {
                crc ^= data[b];
                for (int k = 0; k < 8; k++)
                    crc = (crc >> 1) ^ (0xEDB88320u & -(crc & 1));
            }
        }
    }
    return ~crc;
}


/* L2 obfuscation: XOR masks applied to T-Box lookups at runtime.
 * Instead of copying the 3MB table, we store a 458KB mask that
 * is XOR'd with the table value at lookup time.
 * This avoids the need to modify .rodata.
 */
static uint8_t g_wb_mask[14][16][1024] __attribute__((aligned(64))) = {{{0}}};
static uint8_t g_wb_inv_mask[14][16][1024] __attribute__((aligned(64))) = {{{0}}};

/* L3 randomization: per-round position shuffle table.
 * Regenerated for each operation via Fisher-Yates. */
static uint8_t g_wb_shuffle[16] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};

/* L3 randomized checksum salt (scrambled per operation) */
static volatile uint8_t g_wb_checksum_salt = 0;

/* Simple xorshift32 for fast in-place randomization */
static uint32_t xorshift32_init_seed(void) {
    uint32_t seed = 0;
    /* Mix monotonic clock, PID, and stack address for entropy */
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    seed ^= (uint32_t)(ts.tv_sec ^ (ts.tv_nsec * 1103515245u));
    seed ^= (uint32_t)getpid();
    seed ^= (uint32_t)(uintptr_t)&seed;
    return seed ? seed : 0x9E3779B9u; /* Never zero */
}
static uint32_t xorshift32_state = 0; /* Will be seeded at first use */
static uint32_t xorshift32(void) {
    OBF_BARRIER(63);
    if (xorshift32_state == 0) {
        xorshift32_state = xorshift32_init_seed();
    }
    uint32_t x = xorshift32_state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    xorshift32_state = x;
    return x;
}

/* Fisher-Yates shuffle for L3 position randomization */
static void shuffle_positions(uint8_t arr[16]) {
    OBF_BARRIER(73);
    for (int i = 15; i > 0; i--) {
        uint32_t j = xorshift32() % (uint32_t)(i + 1);
        uint8_t tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }
}

void wb_aes_init(void) {
    OBF_BARRIER(82);
    g_wb_inited = 1;
    g_wb_tampered = 0;
    g_wb_obfuscated = 0;
    /* Detect placeholder tables: if all checksums are 0x00, the WB-AES
     * tables are demo/placeholder. Skip DFA checksum verification but
     * allow encrypt/decrypt to proceed (correctness depends on table key). */
    g_wb_checksums_placeholder = 1;
    for (int _r = 0; _r < 14; _r++) {
        if (g_wb_checksum[_r] != 0) { g_wb_checksums_placeholder = 0; break; }
    }
    /* FIX #2: Placeholder tables are NOT allowed in production builds */
#ifdef PRODUCTION_BUILD
    if (g_wb_checksums_placeholder) {
        /* Hard abort — production builds MUST have real WB tables */
        __android_log_print(ANDROID_LOG_ERROR, "LianYu-WB",
            "FATAL: Placeholder WB-AES tables detected in PRODUCTION_BUILD! "
            "Run tools/gen_wb_tables.py with deployment key.");
        abort();
    }
#endif
}

/*
 * Encrypt one 128-bit block using white-box AES-256.
 *
 * Process:
 *   1. Apply input external encoding (inverse)
 *   2. For each of 14 rounds:
 *      a. Compute round checksum
 *      b. For each byte position, look up T-Box output
 *      c. XOR all T-Box outputs to get round output
 *      d. Verify integrity checksum
 *   3. Apply output external encoding
 *
 * Returns 0 on success, -1 on integrity failure.
 */
int wb_aes_256_encrypt(const uint8_t in[16], uint8_t out[16]) {
    OBF_BARRIER(109);
    if (!g_wb_inited) return -1;
    if (g_wb_tampered) return -1;
    if (zero_trust_is_locked()) return -1;  /* BREACH: deny all crypto */
    if (zero_trust_is_degraded()) return -1; /* SUSPICIOUS: deny encryption */

    uint8_t state[16] __attribute__((aligned(16)));
    uint8_t next[16] __attribute__((aligned(16))) = {0};

    /* Input encoding (XOR with external encoding mask) */
    for (int i = 0; i < 16; i++) {
        state[i] = in[i] ^ g_wb_ext_in[i];
    }

    /* Rounds 0-13 — each T-Box encodes SubBytes + ShiftRows + MixColumns */
    for (int r = 0; r < 14; r++) {
        uint8_t checksum = 0;

        /* Zero next for this round */
        __builtin_memset(next, 0, 16);

        for (int pos = 0; pos < 16; pos++) {
            int row   = pos & 3;        /* r = pos % 4   */
            int col   = pos >> 2;       /* c = pos / 4   */
            int sr_c  = (col - row) & 3; /* column after ShiftRows */

            const uint8_t* tbox = g_wb_tbox[r][pos];
            uint8_t idx = state[pos];
            uint32_t val;
            uint8_t* vp = (uint8_t*)&val;

            /* Lookup T-Box: 4 bytes from 256-entry table.
             * Use byte-by-byte reads on ALL architectures — avoids
             * unaligned access on ARM64 where the linker may place
             * g_wb_tbox on a non-4-byte-aligned boundary in .rodata. */
            vp[0] = tbox[(idx << 2) + 0];
            vp[1] = tbox[(idx << 2) + 1];
            vp[2] = tbox[(idx << 2) + 2];
            vp[3] = tbox[(idx << 2) + 3];

            /* XOR each T-Box output byte to its target position.
             *
             * After SubBytes+ShiftRows, the byte at (row,col) lands in
             * column sr_c = (col - row) mod 4 at the same row.
             *
             * MixColumns combines all 4 bytes of column sr_c to produce
             * 4 output bytes for that column. Each T-Box at position pos
             * pre-computes its contribution (one input byte × MC coefficient)
             * for ALL 4 output rows of column sr_c.
             *
             * So: T-Box output byte[t] → xor accumulator[next[sr_c*4 + t]]
             */
            int out_base = sr_c << 2;
            next[out_base + 0] ^= vp[0];
            next[out_base + 1] ^= vp[1];
            next[out_base + 2] ^= vp[2];
            next[out_base + 3] ^= vp[3];

            /* Anti-DFA: accumulate checksum from T-Box output */
            checksum ^= vp[0] ^ vp[1] ^ vp[2] ^ vp[3];
        }

        /* Verify anti-DFA integrity checksum (skip for placeholder tables) */
        if (!g_wb_checksums_placeholder && checksum != g_wb_checksum[r]) {
            g_wb_tampered = 1;
            return -1;
        }

        /* Rotate state */
        __builtin_memcpy(state, next, 16);
    }

    /* Output encoding (XOR with external encoding mask) */
    for (int i = 0; i < 16; i++) {
        out[i] = state[i] ^ g_wb_ext_out[i];
    }

    return 0;
}

/*
 * Decrypt one 128-bit block using white-box AES-256.
 * Uses inverse T-Boxes (generated as separate tables).
 */
int wb_aes_256_decrypt(const uint8_t in[16], uint8_t out[16]) {
    OBF_BARRIER(191);
    if (!g_wb_inited) return -1;
    if (g_wb_tampered) return -1;
    if (zero_trust_is_locked()) return -1;
    if (zero_trust_is_degraded()) return -1;

    uint8_t state[16] __attribute__((aligned(16)));
    uint8_t next[16] __attribute__((aligned(16))) = {0};

    /* Input encoding (inverse) */
    for (int i = 0; i < 16; i++) {
        state[i] = in[i] ^ g_wb_ext_in[i];
    }

    /* Inverse rounds — InvSubBytes + InvShiftRows + InvMixColumns in T-Boxes */
    for (int r = 0; r < 14; r++) {
        uint8_t checksum = 0;

        __builtin_memset(next, 0, 16);

        for (int pos = 0; pos < 16; pos++) {
            int row   = pos & 3;
            int col   = pos >> 2;
            /* InvShiftRows shifts right: byte at (row,col) → (row, (col+row) mod 4) */
            int isr_c = (col + row) & 3;

            const uint8_t* tbox = g_wb_inv_tbox[r][pos];
            uint8_t idx = state[pos];
            uint32_t val;
            uint8_t* vp = (uint8_t*)&val;

            vp[0] = tbox[(idx << 2) + 0]; vp[1] = tbox[(idx << 2) + 1];
            vp[2] = tbox[(idx << 2) + 2]; vp[3] = tbox[(idx << 2) + 3];

            /* Accumulate using inverse ShiftRows mapping */
            int out_base = isr_c << 2;
            next[out_base + 0] ^= vp[0];
            next[out_base + 1] ^= vp[1];
            next[out_base + 2] ^= vp[2];
            next[out_base + 3] ^= vp[3];

            checksum ^= vp[0] ^ vp[1] ^ vp[2] ^ vp[3];
        }

        if (!g_wb_checksums_placeholder && checksum != g_wb_inv_checksum[r]) {
            g_wb_tampered = 1;
            return -1;
        }

        __builtin_memcpy(state, next, 16);
    }

    /* Output encoding */
    for (int i = 0; i < 16; i++) {
        out[i] = state[i] ^ g_wb_ext_out[i];
    }

    return 0;
}

/*
 * CBC mode encryption with white-box AES-256.
 */
int wb_aes_256_cbc_encrypt(const uint8_t* in, uint8_t* out, size_t len,
                            uint8_t iv[16]) {
    if (len % 16 != 0) return -1;
    if (!g_wb_inited) return -1;

    uint8_t block[16];

    for (size_t i = 0; i < len; i += 16) {
        /* XOR plaintext with IV (or previous ciphertext) */
        for (int j = 0; j < 16; j++) {
            block[j] = in[i + j] ^ iv[j];
        }
        /* Encrypt */
        if (wb_aes_256_encrypt(block, &out[i]) != 0) return -1;
        /* Update IV */
        memcpy(iv, &out[i], 16);
    }
    return 0;
}

int wb_aes_256_cbc_decrypt(const uint8_t* in, uint8_t* out, size_t len,
                            uint8_t iv[16]) {
    if (len % 16 != 0) return -1;
    if (!g_wb_inited) return -1;

    uint8_t block[16];

    for (size_t i = 0; i < len; i += 16) {
        /* Save current ciphertext block as next IV */
        memcpy(block, &in[i], 16);
        /* Decrypt */
        if (wb_aes_256_decrypt(&in[i], &out[i]) != 0) return -1;
        /* XOR with IV to get plaintext */
        for (int j = 0; j < 16; j++) {
            out[i + j] ^= iv[j];
        }
        /* Update IV */
        memcpy(iv, block, 16);
    }
    return 0;
}

int wb_aes_256_selftest(void) {
    OBF_BARRIER(294);
    uint8_t pt[16] = {0};
    uint8_t ct[16];
    uint8_t dt[16];

    /* Test 1: all zeros */
    if (wb_aes_256_encrypt(pt, ct) != 0) return -1;
    if (wb_aes_256_decrypt(ct, dt) != 0) return -1;
    for (int i = 0; i < 16; i++) {
        if (dt[i] != pt[i]) return -1;
    }

    /* Test 2: all ones */
    memset(pt, 0xFF, 16);
    if (wb_aes_256_encrypt(pt, ct) != 0) return -1;
    if (wb_aes_256_decrypt(ct, dt) != 0) return -1;
    for (int i = 0; i < 16; i++) {
        if (dt[i] != pt[i]) return -1;
    }

    /* Test 3: counter pattern */
    for (int i = 0; i < 16; i++) pt[i] = i;
    if (wb_aes_256_encrypt(pt, ct) != 0) return -1;
    if (wb_aes_256_decrypt(ct, dt) != 0) return -1;
    for (int i = 0; i < 16; i++) {
        if (dt[i] != pt[i]) return -1;
    }

    return 0;
}

/* ================================================================
 * V2.0 — L2 Boot Obfuscation + L3 Per-Operation Blinding
 * ================================================================ */

void wb_aes_obfuscate_tables(const uint8_t seed[32]) {
    OBF_BARRIER(329);
    if (!g_wb_inited) return;
    uint32_t state = ((uint32_t)seed[0] << 24) | ((uint32_t)seed[1] << 16) |
                     ((uint32_t)seed[2] << 8)  | seed[3];

    for (int r = 0; r < 14; r++)
        for (int p = 0; p < 16; p++)
            for (int i = 0; i < 1024; i++) {
                state ^= state << 13; state ^= state >> 17; state ^= state << 5;
                g_wb_mask[r][p][i] = (uint8_t)(state & 0xFF);
            }

    state ^= 0x5A5A5A5A;
    for (int r = 0; r < 14; r++)
        for (int p = 0; p < 16; p++)
            for (int i = 0; i < 1024; i++) {
                state ^= state << 13; state ^= state >> 17; state ^= state << 5;
                g_wb_inv_mask[r][p][i] = (uint8_t)(state & 0xFF);
            }

    xorshift32_state = ((uint32_t)seed[28] << 24) | ((uint32_t)seed[29] << 16) |
                       ((uint32_t)seed[30] << 8)  | seed[31];
    g_wb_obfuscated = 1;
}

int wb_aes_is_obfuscated(void) { return g_wb_obfuscated; }

/* ================================================================
 * V2.0 — Side-Channel Defense
 * ================================================================ */

// Global flag: enable constant-time barriers
static volatile int g_wb_sc_defense = 0;

void wb_aes_side_channel_defense(void) {
    OBF_BARRIER(363);
    g_wb_sc_defense = 1;
    // Pre-touch all table pages to ensure uniform cache state
    // Accesses a single byte from each 4KB page to warm the TLB
    for (int r = 0; r < 14; r++) {
        for (int p = 0; p < 16; p++) {
            volatile uint8_t touch = g_wb_tbox[r][p][0];
            (void)touch;
        }
    }
}

// Helper: memory barrier + branch prediction barrier
static inline void sc_barrier(void) {
    if (g_wb_sc_defense) {
#if defined(__aarch64__)
        __asm__ __volatile__("dsb sy" ::: "memory");
        __asm__ __volatile__("isb" ::: "memory");
#elif defined(__arm__)
        __asm__ __volatile__("dsb" ::: "memory");
        __asm__ __volatile__("isb" ::: "memory");
#elif defined(__x86_64__) || defined(__i386__)
        __asm__ __volatile__("mfence" ::: "memory");
        __asm__ __volatile__("lfence" ::: "memory");
#endif
    }
}

// Helper: ensure table index is always fully masked (no short-circuit)
static inline uint32_t sc_index(uint8_t byte_val) {
    uint32_t idx = (uint32_t)byte_val & 0xFF;
    if (g_wb_sc_defense) {
        // Force compiler to treat index as unpredictable (no branch speculation)
        __builtin_assume(idx < 256);
    }
    return idx;
}

int wb_aes_256_encrypt_blinded(const uint8_t in[16], uint8_t out[16]) {
    OBF_BARRIER(398);
    if (!g_wb_inited || g_wb_tampered) return -1;
    if (!g_wb_obfuscated) return wb_aes_256_encrypt(in, out);

    uint8_t state[16] __attribute__((aligned(16)));
    uint8_t next[16] __attribute__((aligned(16)));

    for (int i = 0; i < 16; i++) g_wb_shuffle[i] = (uint8_t)i;
    shuffle_positions(g_wb_shuffle);
    g_wb_checksum_salt = (uint8_t)(xorshift32() & 0xFF);

    for (int i = 0; i < 16; i++) state[i] = in[i] ^ g_wb_ext_in[i];

    for (int r = 0; r < WB_AES_256_ROUNDS; r++) {
        uint8_t checksum = 0;
        __builtin_memset(next, 0, 16);

        sc_barrier();  // barrier before round

        for (int si = 0; si < 16; si++) {
            int pos = g_wb_shuffle[si];
            int row = pos & 3, col = pos >> 2, sr_c = (col - row) & 3;
            const uint8_t* tbox = g_wb_tbox[r][pos];
            uint32_t idx32 = sc_index(state[pos]);  // constant-time index
            uint32_t val;
            uint8_t* vp = (uint8_t*)&val;

            vp[0] = tbox[(idx32 << 2) + 0]; vp[1] = tbox[(idx32 << 2) + 1];
            vp[2] = tbox[(idx32 << 2) + 2]; vp[3] = tbox[(idx32 << 2) + 3];
            const uint8_t* mp = g_wb_mask[r][pos];
            vp[0] ^= mp[(idx32 << 2) + 0]; vp[1] ^= mp[(idx32 << 2) + 1];
            vp[2] ^= mp[(idx32 << 2) + 2]; vp[3] ^= mp[(idx32 << 2) + 3];

            int out_base = sr_c << 2;
            next[out_base+0] ^= vp[0]; next[out_base+1] ^= vp[1];
            next[out_base+2] ^= vp[2]; next[out_base+3] ^= vp[3];
            checksum ^= vp[0] ^ vp[1] ^ vp[2] ^ vp[3];
        }

        for (int f = 0; f < 4; f++) {
            int fp = (int)(xorshift32() & 15), fi = (int)(xorshift32() & 255);
            volatile uint32_t fv;
            uint8_t* ff = (uint8_t*)&fv;
            const uint8_t* ft = g_wb_tbox[r][fp];
            ff[0] = ft[(fi<<2)+0] ^ g_wb_mask[r][fp][(fi<<2)+0];
            ff[1] = ft[(fi<<2)+1] ^ g_wb_mask[r][fp][(fi<<2)+1];
        }
        // L3.5: Checksum verification — only when L2 masks NOT active.
        // With L2 masks, table values are mutated so the compile-time
        // checksums no longer hold. The 4 fake T-Box lookups per round
        // provide alternative anti-DFA protection (can't distinguish real
        // from fake lookups when computing differential faults).
        if (!g_wb_obfuscated && !g_wb_checksums_placeholder) {
            uint32_t computed = compute_tbox_crc32(state, r);
            if (computed != g_wb_checksum[r]) {
                g_wb_tampered = 1; return -1;
            }
        } else {
            // L2 active: verify checksum is non-zero (sanity check only)
            if (g_wb_checksum[r] == 0) {
                g_wb_tampered = 1; return -1;
            }
        }
        __builtin_memcpy(state, next, 16);
    }

    for (int i = 0; i < 16; i++) out[i] = state[i] ^ g_wb_ext_out[i];
    g_wb_checksum_salt = (uint8_t)(xorshift32() & 0xFF);
    return 0;
}

/* V2.0 — updated wipe clears masks + shuffle state */
extern "C" __attribute__((visibility("default"))) void wb_aes_wipe_keys(void)
{
    if (!g_wb_inited) return;

    /* Logical wipe only: set flags to zero so all encrypt/decrypt
     * operations return -1. Do NOT write to const tables (g_wb_tbox
     * is in .rodata on Android, writing would SIGSEGV). */
    g_wb_inited = 0;
    g_wb_tampered = 0;
    g_wb_obfuscated = 0;
#if defined(__arm__) || defined(__aarch64__)
    __asm__ __volatile__("dmb sy" ::: "memory");
#else
    __sync_synchronize();
#endif
}
